import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";



export default function Home({news, randomUsersResults}) {
  return (
      <>
      <Head>
        <title>Twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <main className='flex min-h-screen mx-auto'>
        {/*making sidebar*/}
          <Sidebar />

              {/*making main section or Feed*/}
              <Feed />

              {/*making widget*/}
                  <Widgets news={news.articles} randomUser={randomUsersResults.results} />

          </main>
    </>
  )
}

//news api      get server side props
export async function getServerSideProps() {
    const news = await fetch(
        "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
    ).then((res) => res.json());


    // who to follow api
    const randomUsersResults = await fetch(
        "https://randomuser.me/api/?results=30&inc=name,login,picture"
    ).then((res) => res.json());


    return {
        props : {
            news,
            randomUsersResults
        }
    }

}
