import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
      <>
      <Head>
        <title>Twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <div className='w-full h-screen '>
        {/*making sidebar*/}
          <Sidebar />


          </div>
    </>
  )
}
