import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";

export default function Home() {
  return (
      <>
      <Head>
        <title>Twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <div className='w-full h-screen flex'>
        {/*making sidebar*/}
          <Sidebar />

              {/*making main section or Feed*/}
              <Feed />

              {/*making widget*/}
              <section className='p-4'>
                  fff
              </section>
          </div>
    </>
  )
}
